name: Build and Push Junit Test Cases Image

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: |
        cd junittestcases
        mvn clean install

    - name: Print Directory Contents
      run: |
        ls -R
        ls -R junittestcases/target

    - name: Include target directory
      run: |
        mv junittestcases/target .

    - name: Build Docker Image
      run: |
        docker build -f junittestcases/Dockerfile -t aratimahe/junittestcases:latest .

        docker images

    - name: Test Case Stage
      run: |
        # Add your test cases here
        # Example: mvn test

    - name: Docker Login to JFrog
      run: echo ${{ secrets.JF_PASSWORD }} | docker login -u ${{ secrets.JF_USER }} --password-stdin githubactionsjfrog.jfrog.io

    - name: Docker Tag
      run: docker tag aratimahe/junittestcases githubactionsjfrog.jfrog.io/junittestcasesrepo/aratimahe/junittestcases:latest

    - name: Docker Push to JFrog
      run: docker push githubactionsjfrog.jfrog.io/junittestcasesrepo/aratimahe/junittestcases:latest
